vich_uploader:
    db_driver: orm

    mappings:
        profil_image:
            uri_prefix: /images/assets/profils
            upload_destination: '%kernel.project_dir%/public/assets/profils'
            namer:  Vich\UploaderBundle\Naming\SmartUniqueNamer
