vich_uploader:
    db_driver: orm

    mappings:
        profil_image:
            uri_prefix: '%uploads_path%'
            upload_destination: '%kernel.project_dir%/public/%uploads_path%'

            inject_on_load: false;
            delete_on_update: false;
            delete_on_remove: false;
